services:
  fintech-postgresql:
    image: bitnami/postgresql
    container_name: fintech-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fintech